[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/workspace/datasets/my_dataset/images"
cache_directory = "/workspace/datasets/my_dataset/cache"
num_repeats = 1
# TQD only:
# tqd_score_file = "/workspace/datasets/my_dataset/scores.tqd.jsonl"
